---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-server
  namespace: web-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
    name: http
  selector:
    app.kubernetes.io/name: simple-web-server
